version: '1.0'
services:
  web:
    build: './build/php/'
    ports:
      - "80:80"
    volumes:
      - ~/vc_dev_web/PHP/app:/var/www/html
    links:
      - db:db
  db:
    build: './build/mysql/'
    volumes:
      - ~/.docker/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=thisisapassworddamned
  myadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    links:
      - db:db